# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: SonarAzure

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'ServiceConnectSonarCloud'
    organization: 'sonarcloudjc'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'sonarcloudjc_manual'
    cliProjectName: 'manual'
    cliSources: '.'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME'


- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'